CREATE TABLE CLIENTES (
	id INTEGER,
	nome VARCHAR(255) NOT NULL,
	idade INTEGER NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	PRIMARY KEY (id, idade)
) PARTITION BY RANGE (idade)

CREATE SEQUENCE cliente_sequence
	start 1
	increment 1

CREATE TABLE CLIENTES_ATE_25 PARTITION OF CLIENTES
	FOR VALUES FROM (MINVALUE) TO (25)
	
CREATE TABLE CLIENTES_25_75 PARTITION OF CLIENTES
	FOR VALUES FROM (25) TO (75)

CREATE TABLE CLIENTES_MAIS_75 PARTITION OF CLIENTES
	FOR VALUES FROM (75) TO (MAXVALUE)
	
INSERT INTO CLIENTES VALUES (nextval('cliente_sequence'), 'nome', 1, 'xxxxxxxxxxx')

select tableoid::regclass, * from clientes order by id